#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build --build-arg ACCESS_KEY=${ACCESS_KEY} --build-arg SECRET_KEY=${SECRET_KEY} . -t $DOCKER_USERNAME/ticket
docker push $DOCKER_USERNAME/ticket