security:
  jwt:
    auth-header-name: Authorization
    aws:
      user-pool-id: ${AWS_COGNITO_USER_POOL_ID}
      region: ap-northeast-2
      cognito-identity-pool-url:
      cognito-identity-pool-url-suffix:
      jwkUrl:
      user-name-field: cognito:username
      groups-field: cognito:groups
      connection-timeout: 2000
      read-timeout: 2000